// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJyeqaBmGwWe-_eIhEMNK5IgfVqohkW3o',
    appId: '1:947596886739:web:36252f6c96a89aae0e4a26',
    messagingSenderId: '947596886739',
    projectId: 'floodalertapp01',
    authDomain: 'floodalertapp01.firebaseapp.com',
    storageBucket: 'floodalertapp01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgt66AY0FMhIzutpTq7Xsovtfy9WPSLfY',
    appId: '1:947596886739:android:f09fd16b77f8b6940e4a26',
    messagingSenderId: '947596886739',
    projectId: 'floodalertapp01',
    storageBucket: 'floodalertapp01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnm-07NovnPtXGOfRrVFu7ZqAK99o8WeU',
    appId: '1:947596886739:ios:cd33009bc03ce8890e4a26',
    messagingSenderId: '947596886739',
    projectId: 'floodalertapp01',
    storageBucket: 'floodalertapp01.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnm-07NovnPtXGOfRrVFu7ZqAK99o8WeU',
    appId: '1:947596886739:ios:cd33009bc03ce8890e4a26',
    messagingSenderId: '947596886739',
    projectId: 'floodalertapp01',
    storageBucket: 'floodalertapp01.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJyeqaBmGwWe-_eIhEMNK5IgfVqohkW3o',
    appId: '1:947596886739:web:f7045d9b12aa95040e4a26',
    messagingSenderId: '947596886739',
    projectId: 'floodalertapp01',
    authDomain: 'floodalertapp01.firebaseapp.com',
    storageBucket: 'floodalertapp01.firebasestorage.app',
  );
}
